//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPhoneBook.DataBaseAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebPhoneBookDBEntities : DbContext
    {
        public WebPhoneBookDBEntities()
            : base("name=WebPhoneBookDBEntities")
        {
        }

        public WebPhoneBookDBEntities(string strConnection)
            : base(strConnection)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PhoneBook> PhoneBookSet { get; set; }
    }
}
